// <auto-generated />
using System;
using AdvancedProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvancedProject.Migrations
{
    [DbContext(typeof(APContext))]
    [Migration("20260415162248_ModifiedRequestData")]
    partial class ModifiedRequestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvancedProject.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AmenityId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            Name = "Parking"
                        },
                        new
                        {
                            AmenityId = 2,
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            AmenityId = 3,
                            Name = "Gym"
                        },
                        new
                        {
                            AmenityId = 4,
                            Name = "Security"
                        },
                        new
                        {
                            AmenityId = 5,
                            Name = "Elevator"
                        },
                        new
                        {
                            AmenityId = 6,
                            Name = "Central AC"
                        },
                        new
                        {
                            AmenityId = 7,
                            Name = "WiFi"
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.Duration", b =>
                {
                    b.Property<int>("DurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DurationId"));

                    b.Property<int>("Months")
                        .HasColumnType("int");

                    b.HasKey("DurationId");

                    b.ToTable("Durations");

                    b.HasData(
                        new
                        {
                            DurationId = 1,
                            Months = 6
                        },
                        new
                        {
                            DurationId = 2,
                            Months = 12
                        },
                        new
                        {
                            DurationId = 3,
                            Months = 24
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.Lease", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaseId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DurationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("LeaseId");

                    b.HasIndex("DurationId");

                    b.HasIndex(new[] { "TenantId" }, "IX_Leases_TenantId");

                    b.HasIndex(new[] { "UnitId" }, "IX_Leases_UnitId");

                    b.ToTable("Leases");

                    b.HasData(
                        new
                        {
                            LeaseId = 1,
                            CreatedAt = new DateTime(2026, 2, 2, 13, 22, 17, 0, DateTimeKind.Unspecified),
                            DurationId = 1,
                            EndDate = new DateTime(2026, 12, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyRent = 300m,
                            StartDate = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            TenantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            LeaseId = 2,
                            CreatedAt = new DateTime(2026, 3, 5, 6, 44, 3, 0, DateTimeKind.Unspecified),
                            DurationId = 1,
                            EndDate = new DateTime(2026, 6, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyRent = 500m,
                            StartDate = new DateTime(2026, 7, 1, 12, 6, 12, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            TenantId = 2,
                            UnitId = 3
                        },
                        new
                        {
                            LeaseId = 3,
                            CreatedAt = new DateTime(2026, 3, 10, 7, 52, 33, 0, DateTimeKind.Unspecified),
                            DurationId = 3,
                            EndDate = new DateTime(2027, 3, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyRent = 350m,
                            StartDate = new DateTime(2026, 3, 10, 11, 1, 22, 0, DateTimeKind.Unspecified),
                            Status = "Terminated",
                            TenantId = 3,
                            UnitId = 1
                        },
                        new
                        {
                            LeaseId = 4,
                            CreatedAt = new DateTime(2026, 2, 5, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DurationId = 2,
                            EndDate = new DateTime(2027, 3, 14, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyRent = 550m,
                            StartDate = new DateTime(2026, 3, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            TenantId = 4,
                            UnitId = 4
                        },
                        new
                        {
                            LeaseId = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 4, 32, 29, 0, DateTimeKind.Unspecified),
                            DurationId = 3,
                            EndDate = new DateTime(2028, 1, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyRent = 250m,
                            StartDate = new DateTime(2026, 2, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            TenantId = 5,
                            UnitId = 5
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.LeaseApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ApproveTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("DurationId");

                    b.HasIndex(new[] { "TenantId" }, "IX_LeaseApplications_TenantId");

                    b.HasIndex(new[] { "UnitId" }, "IX_LeaseApplications_UnitId");

                    b.ToTable("LeaseApplications");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            ApplicationDate = new DateTime(2026, 2, 1, 20, 30, 33, 0, DateTimeKind.Unspecified),
                            ApproveTime = new DateTime(2026, 2, 2, 13, 22, 17, 0, DateTimeKind.Unspecified),
                            DurationId = 1,
                            StartDate = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            TenantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            ApplicationId = 2,
                            ApplicationDate = new DateTime(2026, 2, 3, 3, 7, 12, 0, DateTimeKind.Unspecified),
                            DurationId = 3,
                            StartDate = new DateTime(2026, 5, 5, 18, 9, 24, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TenantId = 2,
                            UnitId = 2
                        },
                        new
                        {
                            ApplicationId = 3,
                            ApplicationDate = new DateTime(2026, 2, 5, 5, 24, 13, 0, DateTimeKind.Unspecified),
                            DurationId = 1,
                            RejectTime = new DateTime(2026, 2, 22, 3, 17, 29, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2027, 1, 1, 9, 10, 22, 0, DateTimeKind.Unspecified),
                            Status = "Rejected",
                            TenantId = 3,
                            UnitId = 3
                        },
                        new
                        {
                            ApplicationId = 4,
                            ApplicationDate = new DateTime(2026, 2, 2, 22, 55, 2, 0, DateTimeKind.Unspecified),
                            ApproveTime = new DateTime(2026, 2, 5, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DurationId = 2,
                            StartDate = new DateTime(2026, 3, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            TenantId = 4,
                            UnitId = 4
                        },
                        new
                        {
                            ApplicationId = 5,
                            ApplicationDate = new DateTime(2026, 2, 9, 9, 33, 11, 0, DateTimeKind.Unspecified),
                            DurationId = 2,
                            StartDate = new DateTime(2026, 4, 20, 14, 22, 5, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TenantId = 5,
                            UnitId = 5
                        },
                        new
                        {
                            ApplicationId = 6,
                            ApplicationDate = new DateTime(2026, 3, 3, 10, 21, 10, 0, DateTimeKind.Unspecified),
                            ApproveTime = new DateTime(2026, 3, 5, 6, 44, 3, 0, DateTimeKind.Unspecified),
                            DurationId = 1,
                            StartDate = new DateTime(2026, 7, 1, 12, 6, 12, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            TenantId = 2,
                            UnitId = 3
                        },
                        new
                        {
                            ApplicationId = 7,
                            ApplicationDate = new DateTime(2026, 1, 12, 6, 10, 9, 0, DateTimeKind.Unspecified),
                            ApproveTime = new DateTime(2026, 3, 11, 7, 52, 33, 0, DateTimeKind.Unspecified),
                            DurationId = 3,
                            StartDate = new DateTime(2026, 3, 10, 11, 1, 22, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            TenantId = 3,
                            UnitId = 1
                        },
                        new
                        {
                            ApplicationId = 8,
                            ApplicationDate = new DateTime(2026, 1, 12, 14, 32, 17, 0, DateTimeKind.Unspecified),
                            ApproveTime = new DateTime(2026, 1, 15, 4, 32, 29, 0, DateTimeKind.Unspecified),
                            DurationId = 3,
                            StartDate = new DateTime(2026, 2, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            TenantId = 5,
                            UnitId = 5
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClosedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InProgressTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ResolvedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex(new[] { "AssignedStaffId" }, "IX_MaintenanceRequests_AssignedStaffId");

                    b.HasIndex(new[] { "SkillId" }, "IX_MaintenanceRequests_SkillId");

                    b.HasIndex(new[] { "TenantId" }, "IX_MaintenanceRequests_TenantId");

                    b.HasIndex(new[] { "UnitId" }, "IX_MaintenanceRequests_UnitId");

                    b.ToTable("MaintenanceRequests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            AssignedStaffId = 1,
                            Notes = "Water leaking from bathroom pipe",
                            Priority = "High",
                            RequestDate = new DateTime(2026, 3, 1, 13, 12, 3, 0, DateTimeKind.Unspecified),
                            SkillId = 1,
                            Status = "Pending",
                            TenantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            RequestId = 2,
                            AssignedStaffId = 2,
                            Notes = "Living room light not working",
                            Priority = "Medium",
                            RequestDate = new DateTime(2026, 3, 2, 23, 12, 42, 0, DateTimeKind.Unspecified),
                            SkillId = 2,
                            Status = "In Progress",
                            TenantId = 2,
                            UnitId = 3
                        },
                        new
                        {
                            RequestId = 3,
                            AssignedStaffId = 3,
                            Notes = "AC cooling is weak",
                            Priority = "Low",
                            RequestDate = new DateTime(2026, 3, 3, 20, 20, 4, 0, DateTimeKind.Unspecified),
                            SkillId = 3,
                            Status = "Resolved",
                            TenantId = 3,
                            UnitId = 1
                        },
                        new
                        {
                            RequestId = 4,
                            AssignedStaffId = 4,
                            Notes = "Front door lock is broken",
                            Priority = "High",
                            RequestDate = new DateTime(2026, 3, 4, 2, 44, 11, 0, DateTimeKind.Unspecified),
                            SkillId = 4,
                            Status = "Pending",
                            TenantId = 4,
                            UnitId = 4
                        },
                        new
                        {
                            RequestId = 5,
                            AssignedStaffId = 5,
                            Notes = "Wall paint is fading and peeling",
                            Priority = "Low",
                            RequestDate = new DateTime(2026, 3, 5, 11, 32, 0, 0, DateTimeKind.Unspecified),
                            SkillId = 5,
                            Status = "Closed",
                            TenantId = 5,
                            UnitId = 5
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.MaintenanceStaff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.HasIndex(new[] { "UserId" }, "IX_MaintenanceStaff_UserId");

                    b.ToTable("MaintenanceStaff");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            AvailabilityStatus = "Available",
                            UserId = 7
                        },
                        new
                        {
                            StaffId = 2,
                            AvailabilityStatus = "Busy",
                            UserId = 8
                        },
                        new
                        {
                            StaffId = 3,
                            AvailabilityStatus = "Available",
                            UserId = 9
                        },
                        new
                        {
                            StaffId = 4,
                            AvailabilityStatus = "Available",
                            UserId = 10
                        },
                        new
                        {
                            StaffId = 5,
                            AvailabilityStatus = "Busy",
                            UserId = 11
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex(new[] { "UserId" }, "IX_Notifications_UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 10, 33, 21, 0, DateTimeKind.Unspecified),
                            Message = "A new lease application has been submitted.",
                            NotificationTypeId = 2,
                            Title = "New Lease Application",
                            UserId = 1
                        },
                        new
                        {
                            NotificationId = 2,
                            CreatedAt = new DateTime(2026, 2, 3, 9, 18, 55, 0, DateTimeKind.Unspecified),
                            Message = "Your lease application has been approved.",
                            NotificationTypeId = 2,
                            Title = "Application Approved",
                            UserId = 2
                        },
                        new
                        {
                            NotificationId = 3,
                            CreatedAt = new DateTime(2026, 3, 2, 14, 25, 14, 0, DateTimeKind.Unspecified),
                            Message = "Your maintenance request status has been updated.",
                            NotificationTypeId = 3,
                            Title = "Maintenance Update",
                            UserId = 3
                        },
                        new
                        {
                            NotificationId = 4,
                            CreatedAt = new DateTime(2026, 3, 12, 13, 44, 21, 0, DateTimeKind.Unspecified),
                            Message = "Your payment has been successfully received.",
                            NotificationTypeId = 4,
                            Title = "Payment Received",
                            UserId = 4
                        },
                        new
                        {
                            NotificationId = 5,
                            CreatedAt = new DateTime(2026, 3, 15, 21, 4, 17, 0, DateTimeKind.Unspecified),
                            Message = "Your lease is now active.",
                            NotificationTypeId = 1,
                            Title = "Lease Activated",
                            UserId = 5
                        },
                        new
                        {
                            NotificationId = 6,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 6, 33, 0, DateTimeKind.Unspecified),
                            Message = "You have been assigned a new maintenance request.",
                            NotificationTypeId = 3,
                            Title = "New Assignment",
                            UserId = 7
                        },
                        new
                        {
                            NotificationId = 7,
                            CreatedAt = new DateTime(2026, 3, 2, 8, 15, 32, 0, DateTimeKind.Unspecified),
                            Message = "Maintenance work is now in progress.",
                            NotificationTypeId = 3,
                            Title = "Work In Progress",
                            UserId = 8
                        },
                        new
                        {
                            NotificationId = 8,
                            CreatedAt = new DateTime(2026, 3, 3, 21, 17, 28, 0, DateTimeKind.Unspecified),
                            Message = "A new HVAC issue has been reported.",
                            NotificationTypeId = 3,
                            Title = "Issue Reported",
                            UserId = 9
                        },
                        new
                        {
                            NotificationId = 9,
                            CreatedAt = new DateTime(2026, 3, 4, 17, 5, 43, 0, DateTimeKind.Unspecified),
                            Message = "A carpentry issue has been reported.",
                            NotificationTypeId = 3,
                            Title = "Issue Reported",
                            UserId = 10
                        },
                        new
                        {
                            NotificationId = 10,
                            CreatedAt = new DateTime(2026, 3, 5, 23, 14, 10, 0, DateTimeKind.Unspecified),
                            Message = "A painting issue has been reported.",
                            NotificationTypeId = 3,
                            Title = "Issue Reported",
                            UserId = 11
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeId = 1,
                            Name = "Lease"
                        },
                        new
                        {
                            NotificationTypeId = 2,
                            Name = "LeaseApplication"
                        },
                        new
                        {
                            NotificationTypeId = 3,
                            Name = "Maintenance"
                        },
                        new
                        {
                            NotificationTypeId = 4,
                            Name = "Payment"
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PaymentId");

                    b.HasIndex(new[] { "LeaseId" }, "IX_Payments_LeaseId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 300m,
                            LeaseId = 1,
                            PaymentDate = new DateTime(2026, 3, 1, 12, 11, 5, 0, DateTimeKind.Unspecified),
                            Status = "Paid"
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 500m,
                            LeaseId = 2,
                            PaymentDate = new DateTime(2026, 3, 5, 9, 33, 12, 0, DateTimeKind.Unspecified),
                            Status = "Paid"
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 350m,
                            LeaseId = 3,
                            PaymentDate = new DateTime(2026, 3, 10, 22, 11, 9, 0, DateTimeKind.Unspecified),
                            Status = "Late"
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 550m,
                            LeaseId = 4,
                            PaymentDate = new DateTime(2026, 3, 12, 7, 15, 22, 0, DateTimeKind.Unspecified),
                            Status = "Paid"
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 250m,
                            LeaseId = 5,
                            PaymentDate = new DateTime(2026, 3, 15, 8, 19, 27, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Block")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<string>("Building")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Road")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.HasKey("PropertyId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            Block = "220",
                            Building = "611",
                            City = "Manama",
                            CreatedAt = new DateTime(2026, 1, 1, 12, 55, 21, 0, DateTimeKind.Unspecified),
                            Description = "A modern residential complex offering comfort and essential amenities.",
                            IsActive = true,
                            Name = "Abraj Al Lulu",
                            Road = "271"
                        },
                        new
                        {
                            PropertyId = 2,
                            Block = "708",
                            Building = "246",
                            City = "Muharraq",
                            CreatedAt = new DateTime(2026, 1, 5, 15, 22, 29, 0, DateTimeKind.Unspecified),
                            Description = "A contemporary tower with modern facilities in a prime location.",
                            IsActive = true,
                            Name = "Almoayyed Tower",
                            Road = "811"
                        },
                        new
                        {
                            PropertyId = 3,
                            Block = "461",
                            Building = "922",
                            City = "Riffa",
                            CreatedAt = new DateTime(2026, 1, 10, 3, 31, 43, 0, DateTimeKind.Unspecified),
                            Description = "A residential property with spacious apartments for families.",
                            IsActive = true,
                            Name = "United Tower",
                            Road = "3062"
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.PropertyManager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ManagerId");

                    b.HasIndex(new[] { "UserId" }, "IX_PropertyManagers_UserId");

                    b.ToTable("PropertyManagers");

                    b.HasData(
                        new
                        {
                            ManagerId = 1,
                            HireDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            Name = "Plumbing"
                        },
                        new
                        {
                            SkillId = 2,
                            Name = "Electrical"
                        },
                        new
                        {
                            SkillId = 3,
                            Name = "HVAC"
                        },
                        new
                        {
                            SkillId = 4,
                            Name = "Carpentry"
                        },
                        new
                        {
                            SkillId = 5,
                            Name = "Painting"
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TenantId");

                    b.HasIndex(new[] { "UserId" }, "IX_Tenants_UserId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            Dob = new DateOnly(2004, 10, 18),
                            NationalId = "041081254",
                            UserId = 2
                        },
                        new
                        {
                            TenantId = 2,
                            Dob = new DateOnly(1995, 3, 26),
                            NationalId = "950306321",
                            UserId = 3
                        },
                        new
                        {
                            TenantId = 3,
                            Dob = new DateOnly(1977, 9, 9),
                            NationalId = "770907721",
                            UserId = 4
                        },
                        new
                        {
                            TenantId = 4,
                            Dob = new DateOnly(1989, 11, 25),
                            NationalId = "891106213",
                            UserId = 5
                        },
                        new
                        {
                            TenantId = 5,
                            Dob = new DateOnly(1982, 7, 18),
                            NationalId = "820752231",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<decimal>("SizeSqFt")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.HasKey("UnitId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex(new[] { "PropertyId" }, "IX_Units_PropertyId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            AvailabilityStatus = "Available",
                            CreatedAt = new DateTime(2026, 1, 1, 4, 12, 55, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 1,
                            RentAmount = 300m,
                            SizeSqFt = 100m,
                            UnitNumber = "A1",
                            UnitTypeId = 1
                        },
                        new
                        {
                            UnitId = 2,
                            AvailabilityStatus = "Occupied",
                            CreatedAt = new DateTime(2026, 1, 2, 23, 16, 33, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 1,
                            RentAmount = 350m,
                            SizeSqFt = 120m,
                            UnitNumber = "A2",
                            UnitTypeId = 1
                        },
                        new
                        {
                            UnitId = 3,
                            AvailabilityStatus = "Available",
                            CreatedAt = new DateTime(2026, 1, 3, 9, 11, 7, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 2,
                            RentAmount = 500m,
                            SizeSqFt = 200m,
                            UnitNumber = "B1",
                            UnitTypeId = 2
                        },
                        new
                        {
                            UnitId = 4,
                            AvailabilityStatus = "Occupied",
                            CreatedAt = new DateTime(2026, 1, 4, 7, 16, 22, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 2,
                            RentAmount = 550m,
                            SizeSqFt = 250m,
                            UnitNumber = "B2",
                            UnitTypeId = 2
                        },
                        new
                        {
                            UnitId = 5,
                            AvailabilityStatus = "Available",
                            CreatedAt = new DateTime(2026, 1, 5, 10, 10, 12, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 1,
                            RentAmount = 250m,
                            SizeSqFt = 80m,
                            UnitNumber = "A3",
                            UnitTypeId = 3
                        },
                        new
                        {
                            UnitId = 6,
                            AvailabilityStatus = "Available",
                            CreatedAt = new DateTime(2026, 1, 6, 4, 15, 45, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PropertyId = 3,
                            RentAmount = 320m,
                            SizeSqFt = 110m,
                            UnitNumber = "C1",
                            UnitTypeId = 1
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.UnitType", b =>
                {
                    b.Property<int>("UnitTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UnitTypeId");

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            UnitTypeId = 1,
                            Name = "Apartment"
                        },
                        new
                        {
                            UnitTypeId = 2,
                            Name = "Office"
                        },
                        new
                        {
                            UnitTypeId = 3,
                            Name = "Studio"
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Username" }, "Unique_Username_Users")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager@mail.com",
                            FullName = "System Manager",
                            Gender = "M",
                            IsActive = true,
                            Password = "Manager123",
                            Phone = "33338876",
                            Role = "Manager",
                            Username = "manager"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 2, 12, 2, 3, 4, 0, DateTimeKind.Unspecified),
                            Email = "zahraa.hubail8@gmail.com",
                            FullName = "Zahraa Hubail",
                            Gender = "F",
                            IsActive = true,
                            Password = "Zahraa.123",
                            Phone = "33735771",
                            Role = "Tenant",
                            Username = "zahraa.hubail"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 3, 15, 15, 12, 55, 0, DateTimeKind.Unspecified),
                            Email = "raghad@gmail.com",
                            FullName = "Raghad Aleskafi",
                            Gender = "F",
                            IsActive = true,
                            Password = "Raghad.123",
                            Phone = "39004266",
                            Role = "Tenant",
                            Username = "raghad.aleskafi"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 3, 20, 6, 11, 2, 0, DateTimeKind.Unspecified),
                            Email = "fatima@gmail.com",
                            FullName = "Fatima Alaiwi",
                            Gender = "F",
                            IsActive = true,
                            Password = "Fatima.123",
                            Phone = "36635578",
                            Role = "Tenant",
                            Username = "fatima.alaiwi"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2026, 3, 25, 5, 15, 27, 0, DateTimeKind.Unspecified),
                            Email = "norain@mail.com",
                            FullName = "Norain Almajed",
                            Gender = "F",
                            IsActive = true,
                            Password = "Norain.123",
                            Phone = "33744063",
                            Role = "Tenant",
                            Username = "norain.almajed"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2026, 3, 28, 7, 17, 22, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.ali@gmail.com",
                            FullName = "Ahmed Ali",
                            Gender = "M",
                            IsActive = true,
                            Password = "Ahmed.999",
                            Phone = "33871125",
                            Role = "Tenant",
                            Username = "ahmed.ali"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2026, 3, 10, 9, 16, 34, 0, DateTimeKind.Unspecified),
                            Email = "alihassan@mail.com",
                            FullName = "Ali Hassan",
                            Gender = "M",
                            IsActive = true,
                            Password = "Ali.123",
                            Phone = "39207552",
                            Role = "Staff",
                            Username = "ali.hassan"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2026, 3, 11, 9, 10, 10, 0, DateTimeKind.Unspecified),
                            Email = "sara.mohamed@gmail.com",
                            FullName = "Sara Mohamed",
                            Gender = "F",
                            IsActive = true,
                            Password = "Sara.888",
                            Phone = "33699152",
                            Role = "Staff",
                            Username = "sara.mohamed"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2026, 3, 12, 10, 2, 15, 0, DateTimeKind.Unspecified),
                            Email = "abbas@gmail.com",
                            FullName = "Abbas Hadi",
                            Gender = "M",
                            IsActive = true,
                            Password = "Abbas.123",
                            Phone = "33546672",
                            Role = "Staff",
                            Username = "abbas.hadi"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2026, 3, 13, 6, 21, 41, 0, DateTimeKind.Unspecified),
                            Email = "layla@gmail.com",
                            FullName = "Layla Yaser",
                            Gender = "F",
                            IsActive = true,
                            Password = "Layla.999",
                            Phone = "39126632",
                            Role = "Staff",
                            Username = "layla.yaser"
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2026, 3, 14, 8, 13, 44, 0, DateTimeKind.Unspecified),
                            Email = "mohammed@gmail.com",
                            FullName = "Mohammed Karim",
                            Gender = "M",
                            IsActive = true,
                            Password = "mohammed.123",
                            Phone = "33921092",
                            Role = "Staff",
                            Username = "mohammed.karim"
                        });
                });

            modelBuilder.Entity("MaintenanceStaffSkill", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("StaffId", "SkillId");

                    b.HasIndex(new[] { "SkillId" }, "IX_MaintenanceStaffSkills_SkillId");

                    b.ToTable("MaintenanceStaffSkills", (string)null);

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            StaffId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            StaffId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            StaffId = 2,
                            SkillId = 3
                        },
                        new
                        {
                            StaffId = 3,
                            SkillId = 1
                        },
                        new
                        {
                            StaffId = 3,
                            SkillId = 4
                        },
                        new
                        {
                            StaffId = 4,
                            SkillId = 5
                        },
                        new
                        {
                            StaffId = 5,
                            SkillId = 3
                        });
                });

            modelBuilder.Entity("UnitAmenity", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("UnitId", "AmenityId");

                    b.HasIndex(new[] { "AmenityId" }, "IX_UnitAmenities_AmenityId");

                    b.ToTable("UnitAmenities", (string)null);

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            AmenityId = 1
                        },
                        new
                        {
                            UnitId = 1,
                            AmenityId = 2
                        },
                        new
                        {
                            UnitId = 1,
                            AmenityId = 4
                        },
                        new
                        {
                            UnitId = 2,
                            AmenityId = 1
                        },
                        new
                        {
                            UnitId = 2,
                            AmenityId = 5
                        },
                        new
                        {
                            UnitId = 3,
                            AmenityId = 3
                        },
                        new
                        {
                            UnitId = 3,
                            AmenityId = 4
                        },
                        new
                        {
                            UnitId = 3,
                            AmenityId = 6
                        },
                        new
                        {
                            UnitId = 4,
                            AmenityId = 4
                        },
                        new
                        {
                            UnitId = 4,
                            AmenityId = 5
                        },
                        new
                        {
                            UnitId = 5,
                            AmenityId = 1
                        },
                        new
                        {
                            UnitId = 5,
                            AmenityId = 7
                        },
                        new
                        {
                            UnitId = 6,
                            AmenityId = 2
                        },
                        new
                        {
                            UnitId = 6,
                            AmenityId = 3
                        },
                        new
                        {
                            UnitId = 6,
                            AmenityId = 4
                        });
                });

            modelBuilder.Entity("AdvancedProject.Models.Lease", b =>
                {
                    b.HasOne("AdvancedProject.Models.Duration", "Duration")
                        .WithMany()
                        .HasForeignKey("DurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvancedProject.Models.Tenant", "Tenant")
                        .WithMany("Leases")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.HasOne("AdvancedProject.Models.Unit", "Unit")
                        .WithMany("Leases")
                        .HasForeignKey("UnitId")
                        .IsRequired();

                    b.Navigation("Duration");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AdvancedProject.Models.LeaseApplication", b =>
                {
                    b.HasOne("AdvancedProject.Models.Duration", "Duration")
                        .WithMany("LeaseApplications")
                        .HasForeignKey("DurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvancedProject.Models.Tenant", "Tenant")
                        .WithMany("LeaseApplications")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.HasOne("AdvancedProject.Models.Unit", "Unit")
                        .WithMany("LeaseApplications")
                        .HasForeignKey("UnitId")
                        .IsRequired();

                    b.Navigation("Duration");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AdvancedProject.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("AdvancedProject.Models.MaintenanceStaff", "AssignedStaff")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("AssignedStaffId");

                    b.HasOne("AdvancedProject.Models.Skill", "Skill")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("SkillId")
                        .IsRequired();

                    b.HasOne("AdvancedProject.Models.Tenant", "Tenant")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("TenantId")
                        .IsRequired();

                    b.HasOne("AdvancedProject.Models.Unit", "Unit")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("UnitId")
                        .IsRequired();

                    b.Navigation("AssignedStaff");

                    b.Navigation("Skill");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AdvancedProject.Models.MaintenanceStaff", b =>
                {
                    b.HasOne("AdvancedProject.Models.User", "User")
                        .WithMany("MaintenanceStaffs")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdvancedProject.Models.Notification", b =>
                {
                    b.HasOne("AdvancedProject.Models.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvancedProject.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdvancedProject.Models.Payment", b =>
                {
                    b.HasOne("AdvancedProject.Models.Lease", "Lease")
                        .WithMany("Payments")
                        .HasForeignKey("LeaseId")
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("AdvancedProject.Models.PropertyManager", b =>
                {
                    b.HasOne("AdvancedProject.Models.User", "User")
                        .WithMany("PropertyManagers")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdvancedProject.Models.Tenant", b =>
                {
                    b.HasOne("AdvancedProject.Models.User", "User")
                        .WithMany("Tenants")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdvancedProject.Models.Unit", b =>
                {
                    b.HasOne("AdvancedProject.Models.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .IsRequired();

                    b.HasOne("AdvancedProject.Models.UnitType", "UnitType")
                        .WithMany("Units")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("MaintenanceStaffSkill", b =>
                {
                    b.HasOne("AdvancedProject.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .IsRequired();

                    b.HasOne("AdvancedProject.Models.MaintenanceStaff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .IsRequired();
                });

            modelBuilder.Entity("UnitAmenity", b =>
                {
                    b.HasOne("AdvancedProject.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .IsRequired();

                    b.HasOne("AdvancedProject.Models.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .IsRequired();
                });

            modelBuilder.Entity("AdvancedProject.Models.Duration", b =>
                {
                    b.Navigation("LeaseApplications");
                });

            modelBuilder.Entity("AdvancedProject.Models.Lease", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("AdvancedProject.Models.MaintenanceStaff", b =>
                {
                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("AdvancedProject.Models.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AdvancedProject.Models.Property", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("AdvancedProject.Models.Skill", b =>
                {
                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("AdvancedProject.Models.Tenant", b =>
                {
                    b.Navigation("LeaseApplications");

                    b.Navigation("Leases");

                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("AdvancedProject.Models.Unit", b =>
                {
                    b.Navigation("LeaseApplications");

                    b.Navigation("Leases");

                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("AdvancedProject.Models.UnitType", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("AdvancedProject.Models.User", b =>
                {
                    b.Navigation("MaintenanceStaffs");

                    b.Navigation("Notifications");

                    b.Navigation("PropertyManagers");

                    b.Navigation("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
