// <auto-generated />
using System;
using AdvancedProjectAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvancedProjectAPI.Migrations
{
    [DbContext(typeof(APContext))]
    [Migration("20260521000001_ExpandPasswordColumn")]
    partial class ExpandPasswordColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Model intentionally omitted — snapshot is authoritative.
            // This migration only alters Users.Password from nvarchar(50) to nvarchar(500).
#pragma warning restore 612, 618
        }
    }
}
